- white_balancer/cfg/white_balancer.cfg
- white_balancer/config/config.yaml
- white_balancer/src/white_balancer.cpp
To fix the timing issue with the Basler cam timings I integrated a time delay parameter in the white balancer.
The Parameter can be easily be changed via dynamic reconfigure.
> Add time stamp delay parameter

- bitbots_vision/launch/vision_startup.launch
This adds a new `camera` parameter to launch file. This parameter determines wether an image provider will be launched (as the `sim` parameter before).
This changes also the behavior of the `debug` parameter: if true, this also activates the publishing of several image messages such as field masks.
> Add camera parameter to launch file

- bitbots_vision/src/bitbots_vision/vision.py
- bitbots_vision/src/bitbots_vision/vision_modules/field_boundary.py
In the reversed field boundary search method the ball often gets detected as a part of the field boundary.
The vision drops balls above the field boundary. Unfortunately, the ball gets dropped most of the time, because the field boundary goes around it. To fix this, I use the convex field boundary to determine if the ball is on our field.
> Switches from normal to convex field boundy for ball filtering.

- bitbots_vision/cfg/Vision.cfg
- bitbots_vision/config/visionparams.yaml
Turn off line detection by creating zero line points.
Currently line points are not needed for further processing, therefore some resources can be saved.
#36 is a reminder to reset this to default.
> Turn off line detection

- bitbots_vision/cfg/Vision.cfg
- bitbots_vision/config/visionparams.yaml
- bitbots_vision/src/bitbots_vision/vision.py
Since the cascade classifier is not in use anymore, this PR removes the usage (but NOT module) of it.
> remove cascade classifier usage from vision

- README.md
- bitbots_vision/cfg/Vision.cfg
- bitbots_vision/config/visionparams.yaml
- bitbots_vision/src/bitbots_vision/vision.py
- bitbots_vision/src/bitbots_vision/vision_modules/color.py
As of this Pull Request, enums for dynamic reconfigure are generated automatically to represent the contents of the respective folder. This has the advantage that typos are avoided and a better overview of the possible values is given. The only drawback is that the vision has to be rebuilt whenever a new color space or model is added.
Since a default has to be selected for enums in dynamic reconfigure, I chose the first file in the folder because it will always be overridden by the default value in the YAML configuration.
This Pull Request was done with the help of @JanGut
> dynamic reconfigure: generate enums for models and color spaces

- bitbots_vision/cfg/Vision.cfg
- bitbots_vision/src/bitbots_vision/vision.py
This is currently untested. It fixes the issue, that the field boundary offset was ignored before when balls were published (even though it was considered in the debug image generation). 
Also it includes a hot fix which allows to ignore the field boundary.
> Ball field boundary offset

- bitbots_vision/src/bitbots_vision/dynamic_color_space.py
- bitbots_vision/src/bitbots_vision/vision.py
Stop loading the color space every time the vision gets a dynamic reconfigure callback.
In addition, this also fixes a log output.
> Stop loading the color space every time

- bitbots_vision/src/bitbots_vision/vision_modules/field_boundary.py
Now we handle tf connectivity exceptions and temporarily switch to the reversed iteration field boundary search method instead if one occurs.
Fixes #102.
> Handle tf connectivity exceptions

- bitbots_vision/config/visionparams.yaml
Adds new parameters for f031 with the Basler camera. I think the f031 parameters should be the default values of the `visionparams.yaml` so it is more userfriendly for non-vision people. This would close #25.
> Params for f031

- bitbots_vision/src/bitbots_vision/vision_modules/lines.py
- bitbots_vision/src/bitbots_vision/vision_modules/yolo_handler.py
This pull request removes unnecessary static methods. There are still some `@staticmethod` decorators left, which I thought where quite useful for the code readability and the namespaces. Fixes #89
> Remove unnecessary static methods

- bitbots_vision/config/visionparams.yaml
Rename the ball topic to balls. See issue #66.
Do not merge before the others are merged.
> Balls instead of ball

- bitbots_vision/CMakeLists.txt
Now the vision extensions are included in the CMake build process.
Closes issue #77
> Add auto build for vision extensions

- bitbots_vision/src/bitbots_vision/vision_modules/candidate.py
- bitbots_vision/src/bitbots_vision/vision_modules/fcnn_handler.py
Since #122, we have changed the name of the rating variable of a candidate. This PR fixes the problem of direct access of a not existing class variable.
> Fix fcnn handler set rating

- white_balancer/CMakeLists.txt
Without `catkin_package()` the dynamic reconfigure header cannot be found.
This pull request closes #130.
> white_balancer: add missing call to catkin_package

- bitbots_vision/src/bitbots_vision/vision_modules/lines.py
Adds correct disabling of line point calculation and the possibility to use the precalculation feature for the line mask. This fixes #143.
> Lines: Add correct compute function

- bitbots_vision/src/bitbots_vision/vision.py
After the function rename, some error occured.
Rename function
> Bug fix in vision.py: Call right function

- README.md
fixed typo "visioparams.yaml" in readme
change visioparams.yaml to visionparams.yaml
None
> fix typo "visioparams.yaml" in readme

- bitbots_vision/package.xml
- bitbots_vision/src/bitbots_vision/dynamic_color_space.py
- bitbots_vision/src/bitbots_vision/vision_modules/color.py
Add the ability to query masks between 1 and 0 to the color detector. 
Add the ability to the color detector, by moving the code from the dynamic color space there,
Is was proposed by @JanGut  in Issue #137.
Closes #137.
> Move mask normalization to color.py

- CMakeLists.txt
This PR removes unneeded old project-identifying files.
The removed file are needed only if the containing folder is a CMake Project or python
package.
The main repo is neither therefore these files should be deleted.
> remove old project-identifying files

- bitbots_vision/package.xml
- bitbots_vision/src/bitbots_vision/vision_modules/field_boundary.py
The kernel aspect ratio was swaped. This pull request fixes it.
I swaped them.
#181
> Field boundary detector: Swap height and width of the kernel

- bitbots_vision/cfg/Vision.cfg
- bitbots_vision/config/visionparams.yaml
- bitbots_vision/src/bitbots_vision/vision.py
- bitbots_vision/src/bitbots_vision/vision_modules/ros_utils.py
- bitbots_vision/src/bitbots_vision/vision_modules/yolo_handler.py
Add dynamic reconfigure for yolo parameters.
- Add parameters to `.cfg` and `.yaml`.
- Add config dict handling to the yolo handler
- Add config param change checks to the `vision.py`
Issue #151 
This pull request should wait for #170 because the changes are in conflict with each other and one of them needs to be merged first, afterwards the other one needs some adjustments. If this one is reviewed faster it could also be merged first.
> Add dynamic reconfigure for yolo params

- bitbots_vision/cfg/Vision.cfg
- bitbots_vision/src/bitbots_vision/vision_modules/field_boundary.py
- bitbots_vision/src/bitbots_vision/vision_modules/lines.py
Adds line detector offset for masks and now also supports negative offset.
The offset parameter was not yet implemented for line masks.
This is also needed for the RoboCup project.
None
> bitbots_vision: lines: Adds line detector offset for masks

- bitbots_vision/launch/record_bag.launch
This PR adds a launch script to record camera rosbags.
- Add launch script file
- #113
> Launch: Add lauch script for rosbag record

- bitbots_vision/package.xml
- bitbots_vision/src/bitbots_vision/vision.py
Changes the `_transfer_image_msg_read_flag` as expected.
Closes #211.
In future, we should use `threading.Lock` instead: #212
~Write documentation~
> Fix transfer image read flag

- bitbots_vision/cfg/Vision.cfg
- bitbots_vision/config/visionparams.yaml
- bitbots_vision/package.xml
- bitbots_vision/src/bitbots_vision/dynamic_color_space.py
This PR ratelimits the dynamic color space node using a new `dynamic_color_space_max_fps` parameter.
Closes #246.
> bitbots_vision: Limit dyn colorspace rate

- bitbots_vision/package.xml
- bitbots_vision/src/bitbots_vision/vision_modules/live_fcnn_03.py
Darknet and OpenVino are currently optional and errors are raised at import time. This also makes tensorflow optional.
> make tensorflow requirement optional

- bitbots_vision/cfg/Vision.cfg
- bitbots_vision/config/visionparams.yaml
- bitbots_vision/src/bitbots_vision/vision.py
- bitbots_vision/src/bitbots_vision/vision_modules/candidate.py
- bitbots_vision/src/bitbots_vision/vision_modules/debug.py
- bitbots_vision/src/bitbots_vision/vision_modules/lines.py
Removes ball and goal post candidates from the line mask.
It also moves the debug drawer in the vision and cleans stuff up.
Closes #265
> Line mask remove ball and goal post candidates

- bitbots_vision/src/bitbots_vision/vision.py
- Use rospy.Rate again
- Increase vision frequency to 130 Hz (double of the camera rate) instead of 100 Hz
Increasing the rate should not be any problem, as the vision does only a few very lightweight checks, if no new image is available.
However, by increasing the rate, we stop wasting 62.5% of our available time to handle an image in the worst case.
> Use rospy rate again and increase rate of vision

- bitbots_vision/launch/vision_startup.launch
- bitbots_vision/package.xml
Reintroduce launch parameter `camera` (defaults to true) to launch the Basler camera alongside the vision.
> Launch basler camera with vision

- bitbots_vision/package.xml
Remove basler camera dependency as we want to to build the vision without camera drivers installed
bit-bots/bitbots_misc/pull/157
> Remove basler camera dependency

- bitbots_vision/docs/index.rst
- bitbots_vision/launch/vision.launch
Vision launch: Remove camera driver launch
Does not start camera anymore.
This was moved to bitbots_bringup vision_standalone.launch
bit-bots/bitbots_misc/pull/159
bit-bots/bitbots_behavior/pull/261
> Vision launch: Remove camera driver launch

- bitbots_vision/bitbots_vision/vision_modules/yoeo_handler.py
String typehints also work, but otherwise it fails at import time when tvm is not installed.
> Fix tvm typehint for when it is not installed

- bitbots_vision/bitbots_vision/yoeo_vision.py
- bitbots_vision/package.xml
global variable "own_team_color" was updated too late in YOEOVision constructor leading to vision components being initialized with "None" instead of the actual team color
> global variable "own_team_color" was updated too late in YOEOVision constructor

- bitbots_vision/docs/index.rst
This PR tries to fix references to manuals in the index of the documentation.
Also adds manuals to the table of contents.
#338
> Docs: Try to fix index

- bitbots_vision/package.xml
As we use the `Cvbridge`, we should depend on it.
- Add `vision_opencv` to the dependencies in `package.xml`
> package.xml: add `vision_opencv` depend
