bit-bots/bitbots_vision

- bitbots_vision/launch/vision_startup.launch
As requested the sim parameter also does not launch an image provider.
> changed behavior of sim launch param

- bitbots_vision/src/bitbots_vision/vision.py
- bitbots_vision/src/bitbots_vision/vision_modules/lines.py
The nonlinepoint detection is disabled. I just commented everything that had to do with it as a quick solution, it has been tested on my computer. For a more practical implementation of less nonlinepoints see the nonlinepoints branch. It is however still WIP and it would be unnecessary work to test that before the World Cup.
> disabled nonlinepoint detection

- bitbots_vision/package.xml
This PR adds some dependencies for the basler camera.
> Add some dependencies for basler camera

- bitbots_vision/cfg/Vision.cfg
- bitbots_vision/config/visionparams.yaml
- bitbots_vision/src/bitbots_vision/vision.py
publishing field boundary for localisation
> Publish field boundary

- bitbots_vision/src/bitbots_vision/vision_modules/ros_utils.py
Prevent publishing of None confidences for goalposts and obstacles.
> Prevent publishing of None confidences

- bitbots_vision/src/bitbots_vision/vision_modules/field_boundary.py
Adds the ball offset option, which was not implemented anymore O.o
> Fix ball offset

- bitbots_vision/src/bitbots_vision/vision.py
Fixes a bug in the reconfiguration of the dynamic color space in the issue #101.
> Fix reconfiguration of dynamic color space

- bitbots_vision/src/bitbots_vision/dynamic_color_space.py
- bitbots_vision/src/bitbots_vision/vision.py
When I discovered the Issue #96 I tried to fix it by improving the thread-safety. This resulted in this pull request. It also fixes issue #90 .
> Vision parallel

- bitbots_vision/src/bitbots_vision/vision.py
- bitbots_vision/src/bitbots_vision/vision_modules/live_fcnn_03.py
Changes some log levels. Also evaluated all the other log levels. Related to issue #61.
> Change log levels

- bitbots_vision/cfg/Vision.cfg
Fix a merge bug with the vision.cfg
> Fix vision cfg

- bitbots_vision/src/bitbots_vision/dynamic_color_space.py
- bitbots_vision/src/bitbots_vision/vision.py
- bitbots_vision/src/bitbots_vision/vision_modules/candidate.py
- bitbots_vision/src/bitbots_vision/vision_modules/color.py
- bitbots_vision/src/bitbots_vision/vision_modules/debug.py
- bitbots_vision/src/bitbots_vision/vision_modules/evaluator.py
- bitbots_vision/src/bitbots_vision/vision_modules/fcnn_handler.py
- bitbots_vision/src/bitbots_vision/vision_modules/field_boundary.py
- bitbots_vision/src/bitbots_vision/vision_modules/live_fcnn_03.py
- bitbots_vision/src/bitbots_vision/vision_modules/obstacle.py
- bitbots_vision/src/bitbots_vision/vision_modules/yolo_handler.py
This PR adds a lot of _underscores for private class methods and variables.
@Flova @NFiedler Please check the marked TODOs.
> Refactor: underscores for private class methods and variables

- bitbots_vision/src/bitbots_vision/vision.py
This todo has been moved to #107.
> bitbots_vision: removed small todo comment

- bitbots_vision/cfg/Vision.cfg
- bitbots_vision/config/simparams.yaml
- bitbots_vision/config/visionparams.yaml
- bitbots_vision/launch/vision_startup.launch
- bitbots_vision/src/bitbots_vision/vision.py
- bitbots_vision/src/bitbots_vision/vision_modules/color.py
- bitbots_vision/src/bitbots_vision/vision_modules/ros_utils.py
Put the sim color selection in the launch file.
Closes #39
> Vision remove sim color parameter 

- bitbots_vision/src/bitbots_vision/vision_modules/yolo_handler.py
> bitbots_vision: yolo_handler: adds getter for candidates

- bitbots_vision/cfg/Vision.cfg
- bitbots_vision/config/visionparams.yaml
- bitbots_vision/src/bitbots_vision/vision_modules/obstacle.py
After the question in the Telegram group, this deactivates the obstacles and lines for version 1 for performance reasons, because they are unused in the current software stack.
> No lines and obstacles

- README.md
- bitbots_vision/cfg/Vision.cfg
- bitbots_vision/config/visionparams.yaml
- bitbots_vision/package.xml
- bitbots_vision/src/bitbots_vision/vision_modules/lines.py
- bitbots_vision/src/bitbots_vision/vision_modules/obstacle.py
- bitbots_vision_tools/package.xml
This PR syncs the parameter description between the parameter cfg and yaml file.
Also fixes typos in param cfg.
Closes #1.
Closes #56.
> bitbots_vision: Sync parameter decription

- bitbots_vision/cfg/Vision.cfg
- bitbots_vision/config/visionparams.yaml
- bitbots_vision/src/bitbots_vision/vision.py
This pull request adds an HSV field color detector, for faster configurations e.g. at demonstrations. Closes #82.
> HSV field color detector

- bitbots_vision/config/visionparams.yaml
Just changes vision settings to RoHow2019 setup
> bitbots_vision: RoHow2019 vision settings

- white_balancer/config/config.yaml
> Add rohow white balance

- bitbots_vision/scripts/save.py
> Save tool: Update debug params.

- bitbots_imageloader/package.xml
- bitbots_imageloader/src/bitbots_imageloader/bitbots_imageloader.py
- bitbots_vision_tools/package.xml
- bitbots_vision_tools/scripts/convert_to_image.py
This pull request updates all shebangs to python3 as we will discuss in our weekly.
> Update shebangs to python3

- bitbots_vision_tools/package.xml
- bitbots_vision_tools/scripts/imgclean.sh
`mkdir` now ignores, if the directory already exists
~- [ ] Run linters~
> bitbots_vision: vision_tools: Ignore existing dir

- README.md
Updates the `readme.md` of the bitbots_vision.
This will be moved to the docs in near future.
> bitbots_vision: Update readme

- bitbots_vision/docs/pyapi/bitbots_vision.rst
- bitbots_vision/docs/pyapi/bitbots_vision.vision_modules.legacy.rst
- bitbots_vision/docs/pyapi/bitbots_vision.vision_modules.rst
- bitbots_vision/package.xml
- bitbots_vision/src/bitbots_vision/vision.py
Improve the handling of new lines in the package description.
Also make constructors and private methods visible.
- change `conf.py`
- adjust new lines in package description
- reset autogen stuff
- add module blacklist to sphinx
- add docs for `vision.py`
> Improve docu system

- bitbots_vision/docs/tutorials/colorpicker.rst
Adds a tutorial for the new color picker.
> Add new color picker docs

- README.md
Update README link to show the ci build documentation.
- Update link
> README: Update link to new CI build documentation

- white_balancer/CMakeLists.txt
- white_balancer/config/config.yaml
- white_balancer/launch/white_balance.launch
- white_balancer/nodelets.xml
- white_balancer/package.xml
- white_balancer/src/white_balancer.cpp
Note: Do not merge, due to problems with the dynamic reconfiguration of multiple nodelet entities.
- Add `nodelet.xml`
- Adjust `package.xml` and `CMakeLists.txt`
- Add class to the `white_balancer.cpp`
- Closes #111
> Make white_balancer a nodelet

- white_balancer/cfg/WhiteBalancer.cfg
- white_balancer/package.xml
Updates python version for `.cfg` file.
~Write documentation~
~Create issues for future work~
> white_balancer: Update cfg py version

- bitbots_vision/package.xml
- bitbots_vision/scripts/dynamic_reconfigure_save.py
Renames the script `save.py` to `dynamic_reconfigure_save.py`.
Updates python version.
Closes #163.
~Write documentation~
> Rename and update save script

- README.md
- Add badge to `README.md`
#34
> Add a CI bagde

- bitbots_vision/cfg/Vision.cfg
- bitbots_vision/config/visionparams.yaml
- bitbots_vision/docs/index.rst
- bitbots_vision/scripts/convert_to_image.py
- bitbots_vision/src/bitbots_vision/vision.py
- bitbots_vision/src/bitbots_vision/vision_modules/obstacle.py
- bitbots_vision/src/bitbots_vision/vision_modules/ros_utils.py
The following packages are adapted to the new message definition:
Tested:
https://github.com/bit-bots/humanoid_league_msgs/pull/14
> bitbots_vision: Adaptions to new humanoid_league_msgs

- bitbots_vision/package.xml
- bitbots_vision/src/bitbots_vision/vision_modules/ros_utils.py
Add logdebug for dynamic parameter changes.
Closes #218
> Logdebug for param change

- bitbots_vision/cfg/Vision.cfg
- bitbots_vision/config/visionparams.yaml
- bitbots_vision/package.xml
- bitbots_vision/src/bitbots_vision/vision.py
Added dynamic reconfigure parameter for the audio topic (as missing before)
Closes #224 
> Add dynamic reconfigure for audio topic

- bitbots_vision/package.xml
- bitbots_vision/src/bitbots_vision/vision_modules/color.py
Adds missing caching for static masks of the DynamicColorDetector.
Closes #215.
> bitbots_vision: Fix caching of static mask

- bitbots_vision/launch/vision_startup.launch
- bitbots_vision/package.xml
Same as https://github.com/bit-bots/bitbots_lowlevel/pull/72
> fix task scheduling

- bitbots_vision/config/simparams.yaml
Use a special yolo version in simulation
> use different yolo in simulation

- bitbots_vision/docs/index.rst
- bitbots_vision/package.xml
- bitbots_vision/scripts/imgclean.sh
The script has a "feature" that is not explained in the comments in the file.
~- [ ] Test on your machine~
> explain in imgclean script that arrow keys can be used too

- bitbots_vision/src/bitbots_vision/vision_modules/color.py
Fix color space renaming.
~- [ ] Test on your machine~
> Fix color space renaming

- bitbots_vision/docs/index.rst
- bitbots_vision/docs/manual/tutorials/colorpicker.rst
> Docs: Fix headings

- bitbots_vision/docs/manual/tutorials/train_yolo.rst
Adds documention of how to train a yolo for ball and goalpost detection.
> documentation about how to train a yolo

- bitbots_vision/docs/manual/tutorials/train_yolo.rst
During training we had this issue multiple times, so it makes sense to explain how to fix it.
> yolodocs: add a troubleshooting option

- bitbots_vision/src/bitbots_vision/vision_modules/field_boundary.py
Moves the `_calculate_field_boundary()` method to the abstract detector.
Closes #199.
> bitbots_vision: Moves the field boundary compute

- bitbots_vision/config/simparams.yaml
Use new yolo in sim. It works better.
> Use wide FOV Yolo trained by Jonas

- bitbots_vision/src/bitbots_vision/dynamic_color_lookup_table.py
- bitbots_vision/src/bitbots_vision/vision.py
replaced time with rospy.rate and rate.sleep in vision.py for both the main loop and the dynamic reconfigure callback
Closes #216 
> changed usage of time in vision.py to rospy.rate

- bitbots_vision/config/simparams.yaml
- bitbots_vision/src/bitbots_vision/vision_modules/field_boundary.py
Computes restep using the roi height,
Closes #180
> Add variable restep for field boundary detector

- bitbots_vision/src/bitbots_vision/vision_modules/color.py
Pull request #272 broke the `color.py` due to a error while resolving the merge conflict. This PR fixes the wrong variable name.
#272
> Fix name issue

- bitbots_vision/config/simparams.yaml
Temporarily increases the yolo confidence theshold, until new model is deployed
> Temporarily increase yolo confidence thesh

- bitbots_vision/src/bitbots_vision/vision_modules/yolo_handler.py
* Adapt for more classes in the future
* Reduce code duplication
> Refactor yolo handler

- Jenkinsfile
- white_balancer/.rdmanifest
This PR adds an `.rdmanifest` file for white_balancer so that it is installable in CI.
It also updates the Jenkinsfile to a newer format so that CI builds the white_balancer package again.
> Update CI config and add rdmanifest file

- bitbots_vision/config/simparams.yaml
- bitbots_vision/src/bitbots_vision/vision.py
- bitbots_vision/src/bitbots_vision/vision_modules/obstacle.py
- bitbots_vision/src/bitbots_vision/vision_modules/yolo_handler.py
* Integrates Intersections and Robots detected by YOLO to the Pipeline.
> Add other YOLO candidate finders

- white_balancer/CMakeLists.txt
This adds the `-Wall -Werror -Wno-unused` flags to the white balancer. No further code changes.
> Use -Wall in white balancer

- bitbots_vision/scripts/bitbots_imageloader.py
- bitbots_vision/src/bitbots_vision/dynamic_color_lookup_table.py
- bitbots_vision/src/bitbots_vision/vision.py
https://github.com/bit-bots/bitbots_misc/pull/122
> change to new rate implementation

- bitbots_vision/src/bitbots_vision/vision.py
Small fix so that this is correctly handled from team comm.
> fix obstacle type to unknown robot

- bitbots_vision/config/simparams.yaml
- Lower Hue in HSV field detection
> Adapt to new Webots lighing settings

- bitbots_vision/bitbots_vision/params.py
- bitbots_vision/bitbots_vision/vision.py
- bitbots_vision/bitbots_vision/vision_modules/ros_utils.py
- bitbots_vision/config/visionparams.yaml
- bitbots_vision/package.xml
> Fix vision

- bitbots_vision/bitbots_vision/vision.py
> Fix wrong duration

- bitbots_vision/config/visionparams.yaml
Temporarily switch to yolo opencv
> Temporarily switch to yolo opencv

- bitbots_vision/bitbots_vision/vision.py
- bitbots_vision/bitbots_vision/vision_modules/ros_utils.py
- bitbots_vision/bitbots_vision/yoeo_vision.py
- bitbots_vision/config/yoeo_visionparams.yaml
- Use the latest model without goal posts
- Use the optimized TVM version (60ms latency at full precision and ~10% CPU load)
- Fix configuration issue.
- Some clean up stuff that was not worth its own pr
> Finalize vision setup for wm

- bitbots_vision/package.xml
added missing dependency "bitbots_utils"
> added missing dependency "bitbots_utils"

- bitbots_vision/bitbots_vision/yoeo_params.py
- bitbots_vision/bitbots_vision/yoeo_vision.py
- bitbots_vision/config/yoeo_visionparams.yaml
- bitbots_vision/config/yoeo_visionparams_sim.yaml
renamed parameter "obstacle_team_color_detection" into "yoeo_team_colors_provided" as it is rather a feature of the utilized YOEO than of the vision
> renamed parameter "obstacle_team_color_detection" 

- bitbots_vision/bitbots_vision/vision_modules/yoeo/yoeo_handlers.py
Nms across multiple robot classes, now for PyTorch. Requires https://github.com/bit-bots/YOEO/pull/95
Requires https://github.com/bit-bots/YOEO/pull/95
> nms across multiple robot classes for pytorch

- bitbots_vision/package.xml
to allow for new features like conditional depends accoring to rep [0149].
We use this to differentiate between dependencies required on robots and in
the simulation.
[149]: https://www.ros.org/reps/rep-0149.html
> fix(package.xml): upgrade to version 3

- bitbots_vision/docs/index.rst
- bitbots_vision/docs/manual/legacy_vision.rst
- bitbots_vision/docs/manual/yoeo_vision.rst
Added documentation for YOEO vision.
I'm not sure whether the references work.
> added documentation for YOEO vision

- bitbots_vision/bitbots_vision/yoeo_vision.py
Previously, we used the throttle node from topic_tools to reduce the frequency of logged images to 1 Hz. Unfortunately, adding this additional subscriber reduces the /camera/image_proc frequency by 30%. To avoid this additional subscription of the throttle node, we republish it in the vision with lower frequency.
https://github.com/bit-bots/bitbots_misc/pull/230
> Add image republishing for rosbags for wm 2023

- bitbots_vision/bitbots_vision/vision_modules/yoeo/__init__.py
- bitbots_vision/bitbots_vision/vision_modules/yoeo/vision_components.py
- bitbots_vision/bitbots_vision/yoeo_params.py
- bitbots_vision/bitbots_vision/yoeo_vision.py
- bitbots_vision/config/yoeo_visionparams.yaml
- bitbots_vision/config/yoeo_visionparams_sim.yaml
Remove the field boundary detection from yoeo vision
Solves https://github.com/bit-bots/bitbots_vision/issues/348
> remove field boundary detection from yoeo vision

- bitbots_vision/bitbots_vision/vision_modules/yoeo/yoeo_handlers.py
Changes are necessary due to https://github.com/bit-bots/YOEO/pull/117
> adapted pytorch handler to changes in yoeo api
